### ISSUE TITLE
Bug Report: Worker crashes when processing ERA5 data on lower-memory machines

### ISSUE THREAD

**Issue by SBeairsto** [climagination/nc2pt#18]
### Summary:
When running the preprocessing pipeline on a remote machine with lower memory (Marvin and Tars), the process fails during ERA5 processing with Dask worker crashes due to memory overload. The same code succeeds on a higher-memory machine (Thufier).

### 🧩 What I'm doing
Running preprocess.py, which:

- Takes high-resolution WRF and low-resolution ERA5 climate variables (netCDF)
- Regrids and interpolates ERA5 data to match the WRF grid
- Coarsens it again
- Normalizes both datasets
- Outputs corresponding paired Zarr datasets for train/val/test

### ✅ Expected Behavior
Pipeline runs successfully and creates .zarr files on both machines.

### ❌ Observed Behavior
On Marvin (lower memory), the pipeline crashes during the Zarr writing step of ERA5 data. It logs multiple warnings like:
- `Worker is at 95% memory usage. Restarting...`
- `KilledWorker: Attempted to run task (...) on 4 different workers, but all those workers died while running it.`

The same error occurs when running the code on a second machine (Tars), which has similar memory constraints as Marvin. 

On Thufier, it completes successfully with the same input files and environment.

### 📋 Reproduction Steps

1. Set up a Conda environment and clone the repository.
2. Place ERA5 and WRF `.nc` files as expected by the config.
3. Use default config.yaml file with update on lines 165-182:
```
select:
  # Time indexing for subsets
  time:
    # Crop to the dataset with the shortest run
    # this defines the full dataset from which to subset
    range:
      start: "20001001T06:00:00"
      end: "20010201T06:00:00"
      # start: "2021-11-01T00:00:00"
      # end: "2021-12-31T22:00:00"

    # use this to select which years to reserve for testing
    # and for validation
    # the remaining years in full will be used for training
    test_years: [2000]
    validation_years: [2000]
    # test_years: [None]
    # validation_years: [None]
```

4. Run:
```
bash
python nc2pt/preprocess.py
```
5. On both Marvin and Tars, the pipeline fails after:
```
bash
✨ Writing test output...
```
with multiple worker restarts and eventually a `KilledWorker` exception.

### 💻 System Information
**Working Machine (Thufier)**
- Memory: ≥16 GB available
- Pipeline completes successfully
- Python 3.10
- Dask version: 2025.1.0
- Distributed version: 2025.1.0
- Xarray version: 2024.11.0
- Zarr version: 2.13.3

**Failing Machine 1 (Marvin)**
- Memory: ~11 GB
- Dask fails during ERA5 Zarr output
- Same conda environment and dataset

**Failing Machine 2 (Tars)**
- Memory: ~10–11 GB
- Same error, almost identical log output to Marvin
- Reproducible failure on second low-memory system

### 🧠 Hypothesis
It seems likely the task graph created during ERA5 interpolation and coarsening is too large for Marvin and Tars’s available memory, leading to repeated worker restarts and eventual failure. This may be related to:
- Large dask task graph serialization size (~40.9 MiB)
- Memory not being released to the OS (unmanaged memory warnings)
- Potential Dask configuration differences between systems?

### Suggested steps
- The size of the task graph may be significantly reduced if we move to naive interpolation methods as outlined in issue #15. I recommend we pursue that avenue first and see if it solves this issue.
