### ISSUE TITLE
Feature Request: Support for Preprocessing Invariant Fields

### ISSUE THREAD

**Issue by SBeairsto** [climagination/nc2pt#32]
**Summary:**  
Add functionality to preprocess invariant fields (e.g., `HGT`, `VEGFRA`, `LANDMASK`) that are stored in separate static `.nc` files (e.g., `CA4km_const.nc`) and align them with the HR or HR reference grid.

**Motivation:**  
Some WRF outputs (e.g., topography) are stored in separate invariant files. These fields:  
- Are on the same grid as HR data (currently),  
- May require spatial cropping to match the training domain,  
- May come from different sources in the future, requiring interpolation or regridding to match the HR reference.

**Proposal:**  
Introduce a new top-level config key:
``` yaml
invariant_fields:
  - name: "HGT"
    path: "/path/to/CA4km_const.nc"
    alternative_names: ["HGT"]
    apply_crop: true
    align_with: "hr_ref"  # Optional: if not aligned to HR grid
    transform: []         # Optional math transforms`
```
And a corresponding function to:  
- Load the field using alternative variable names,  
- Crop it to the same spatial extent as the HR data,  
- Optionally align it to the `hr_ref` field if the grids differ,  
- Apply basic mathematical transformations if needed

**Benefits:**  
- Enables invariant fields to be included as additional model inputs or analysis layers.  
- Maintains consistent preprocessing logic across dynamic and static fields.  
- Prepares the codebase for cross-dataset harmonization if HR and invariant grids diverge.
